#!/bin/sh
# Black-box tests for the compile-class merge gates.
# Run from the repo root: sh scripts/test-precommit-gates.sh
#
# Each case builds a throwaway git repo, mirrors the repo's own hook layout into
# it (src/frontend/.husky/{pre-commit,pre-merge-commit,_/}) and points
# core.hooksPath at the copied husky runner, so `git commit` and `git merge`
# reach the hooks exactly as they do here. A fresh repo per case is deliberate: a
# leftover staged file from an earlier case silently changes the next verdict.
#
# The husky runner .husky/_/h is generated by `pnpm install` and is not tracked,
# so it is absent in a fresh clone or worktree. When present it is copied
# verbatim; otherwise an equivalent stub is written. The load-bearing part is
# `sh -e "$s" "$@"`: running a hook under a bare `sh` (no -e) makes the
# parse-error case falsely look like a pass.
#
# Cases 3 and 6 compile real workspace trees, so the suite takes minutes on a
# cold CARGO_TARGET_DIR. The target dir is shared and persistent, so re-runs are
# warm.

REPO_ROOT=$(pwd)
HOOK="$REPO_ROOT/src/frontend/.husky/pre-commit"
MERGE_HOOK="$REPO_ROOT/src/frontend/.husky/pre-merge-commit"
GATES="$REPO_ROOT/scripts/precommit-rust-gates.sh"
HUSKY_H="$REPO_ROOT/src/frontend/.husky/_/h"
FAILURES=0
SKIPS=0

for f in "$HOOK" "$MERGE_HOOK" "$GATES"; do
  [ -f "$f" ] || { echo "FAIL: $f does not exist"; exit 1; }
done

# Shared, persistent target dir so repeat runs are warm. `pwd -W` because a Git
# Bash /tmp path is not resolvable by cargo, which is a native binary.
TMPROOT="${TMPDIR:-/tmp}"
mkdir -p "$TMPROOT/rusty-gates-target"
CARGO_TARGET_DIR=$(cd "$TMPROOT/rusty-gates-target" && { pwd -W 2>/dev/null || pwd; })
export CARGO_TARGET_DIR

if [ -f "$HUSKY_H" ]; then
  echo "husky runner: real ($HUSKY_H)"
else
  echo "husky runner: stub (.husky/_/h absent - not tracked, generated by pnpm install)"
fi
echo "CARGO_TARGET_DIR=$CARGO_TARGET_DIR"
echo ""

# setup <name>: cd into a fresh scratch repo with the full hook wiring installed.
# NOT a command substitution - `cd` inside $( ) runs in a subshell and would
# leave the caller in the real repo, staging test files into it.
setup() {
  CASE="$1"
  SCRATCH=$(mktemp -d)
  cd "$SCRATCH" || exit 1
  git init -q .
  git config user.name t
  git config user.email t@t
  git config commit.gpgsign false
  # Keep the scratch fixtures byte-identical to what printf wrote, and silence
  # the per-file "LF will be replaced by CRLF" warnings that otherwise bury the
  # real output on Windows.
  git config core.autocrlf false
  mkdir -p src/frontend/.husky/_ scripts
  cp "$HOOK" src/frontend/.husky/pre-commit
  cp "$MERGE_HOOK" src/frontend/.husky/pre-merge-commit
  cp "$REPO_ROOT"/scripts/*.sh scripts/
  if [ -f "$HUSKY_H" ]; then
    cp "$HUSKY_H" src/frontend/.husky/_/h
  else
    cat > src/frontend/.husky/_/h <<'STUB'
#!/usr/bin/env sh
n=$(basename "$0")
s=$(dirname "$(dirname "$0")")/$n
[ ! -f "$s" ] && exit 0
[ "${HUSKY-}" = "0" ] && exit 0
export PATH="node_modules/.bin:$PATH"
sh -e "$s" "$@"
c=$?
[ $c != 0 ] && echo "husky - $n script failed (code $c)"
exit $c
STUB
  fi
  printf '#!/usr/bin/env sh\n. "$(dirname "$0")/h"\n' > src/frontend/.husky/_/pre-commit
  printf '#!/usr/bin/env sh\n. "$(dirname "$0")/h"\n' > src/frontend/.husky/_/pre-merge-commit
  # husky's own _/.gitignore: keeps the generated runner out of `git add -A`,
  # which cases 3 and 6 use.
  printf '*\n' > src/frontend/.husky/_/.gitignore
  chmod 755 src/frontend/.husky/pre-commit src/frontend/.husky/pre-merge-commit \
            src/frontend/.husky/_/h src/frontend/.husky/_/pre-commit \
            src/frontend/.husky/_/pre-merge-commit scripts/*.sh
  git config core.hooksPath src/frontend/.husky/_
}

# mkcrate: a zero-dependency crate in the scratch repo, so cargo check and clippy
# cost about a second instead of compiling the real workspace's dependencies.
mkcrate() {
  printf '[package]\nname = "gatecase"\nversion = "0.0.0"\nedition = "2021"\n\n[lib]\npath = "src/lib.rs"\n' > Cargo.toml
}

# run_gates [args]: invoke the script directly, the way a hook does.
run_gates() {
  OUT=$(sh -e ./scripts/precommit-rust-gates.sh "$@" 2>&1)
  RC=$?
}

check() {
  if [ "$2" != "$3" ]; then
    echo "  FAIL [$CASE] $1: want [$2] got [$3]"
    FAILURES=$((FAILURES + 1))
  fi
}

# contains <label> <needle>: assert $OUT mentions it.
contains() {
  case "$OUT" in
    *"$2"*) ;;
    *) echo "  FAIL [$CASE] $1: output does not contain [$2]"; FAILURES=$((FAILURES + 1)) ;;
  esac
}

missing() {
  case "$OUT" in
    *"$2"*) echo "  FAIL [$CASE] $1: output unexpectedly contains [$2]"; FAILURES=$((FAILURES + 1)) ;;
    *) ;;
  esac
}

teardown() { cd "$REPO_ROOT" || exit 1; rm -rf "$SCRATCH"; }

# conflicted_merge <resolution-body>: build a base commit, two divergent
# branches editing the same line, merge them to a conflict, then write
# <resolution-body> as the resolution and stage it. Leaves MERGE_HEAD in place,
# which is what the pre-commit path keys on.
conflicted_merge() {
  mkcrate
  printf 'pub fn shared() -> i32 {\n    0\n}\n' > src/lib.rs
  git add Cargo.toml src/lib.rs
  git commit -qm base --no-verify
  git checkout -q -b side
  printf 'pub fn shared() -> i32 {\n    1\n}\n' > src/lib.rs
  git commit -qam side --no-verify
  git checkout -q -
  printf 'pub fn shared() -> i32 {\n    2\n}\n' > src/lib.rs
  git commit -qam mainline --no-verify
  git merge side -m merged >/dev/null 2>&1
  printf '%s' "$1" > src/lib.rs
  git add src/lib.rs
}

# realtree <committish>: extract a real workspace tree into the scratch repo and
# stage all of it, so the gates see a merge that touches Rust files.
#
# rusty-docs/src/generated/ is gitignored build-script output, so `git archive`
# never contains it. Cargo only recreates it by re-running rusty-docs' build
# script, and the shared warm CARGO_TARGET_DIR makes cargo consider that script
# fresh -- from a *different* source path, which it does not fingerprint. The
# result is a false E0583 "file not found for module `generated`" that looks
# exactly like a real merge break. Touching the `docs` tree invalidates the
# script's declared `rerun-if-changed=docs` input, which regenerates the module
# while keeping the target dir warm. Measured: without the touch, round 1 of a
# fresh target dir passes and every later round fails; with it, all rounds pass.
realtree() {
  git -C "$REPO_ROOT" archive "$1" | tar -x
  rm -rf scripts
  mkdir -p scripts
  cp "$REPO_ROOT"/scripts/*.sh scripts/
  chmod 755 scripts/*.sh
  [ -d rusty-docs/docs ] && find rusty-docs/docs -type f -exec touch {} +
  git add -A >/dev/null 2>&1
}

echo "1. conflicted merge, unparseable resolution, real husky wiring -> commit blocked"
setup "conflicted-unparseable"
# The 53dff77 shape: a `let` binding with no terminating semicolon.
conflicted_merge 'pub fn shared() -> i32 {
    let x = 1
    let y = 2;
    x + y
}
'
BEFORE=$(git rev-parse HEAD)
OUT=$(git commit -m "Resolve merge conflicts with main" 2>&1); RC=$?
if [ "$RC" -eq 0 ]; then
  echo "  FAIL [$CASE] unparseable merge resolution was committed (exit 0)"
  FAILURES=$((FAILURES + 1))
fi
contains "names the parse error" "expected \`;\`"
check "HEAD unchanged" "$BEFORE" "$(git rev-parse HEAD)"
check "MERGE_HEAD still present" "yes" "$([ -f .git/MERGE_HEAD ] && echo yes || echo no)"
# Assert only "blocked", not which layer blocked: on an unparseable file the
# rustfmt block reaches rustfmt first and dies with 123, so the gates never run.
# That is correct behaviour -- the parse class is the one overlap between the two
# blocks -- but it means this case does not exercise the gates. Case 1b does,
# with MERGE_HEAD still on disk, which is the trigger the gates actually key on.
CARGO_TARGET_DIR="$CARGO_TARGET_DIR" run_gates
CASE="conflicted-unparseable (1b: gates alone)"
check "gates exit" 1 "$RC"
contains "names the parse error" "expected \`;\`"
contains "names the failing gate" "cargo check --workspace' failed"
contains "MERGE_HEAD alone triggered them" "running cargo check --workspace"
teardown

echo "2. same conflicted merge, resolution corrected -> commits"
setup "conflicted-fixed"
conflicted_merge 'pub fn shared() -> i32 {
    let x = 1;
    let y = 2;
    x + y
}
'
BEFORE=$(git rev-parse HEAD)
OUT=$(git commit -m "Resolve merge conflicts with main" 2>&1); RC=$?
check "exit" 0 "$RC"
if [ "$BEFORE" = "$(git rev-parse HEAD)" ]; then
  echo "  FAIL [$CASE] merge was not committed"
  FAILURES=$((FAILURES + 1))
fi
check "both parents recorded" "2" "$(git rev-list --parents -n 1 HEAD | wc -w | tr -d ' ' | awk '{print $1-1}')"
check "resolution committed" "    let x = 1;" "$(git show HEAD:src/lib.rs | sed -n 2p)"
teardown

echo "2b. conflicted merge, resolution deletes a used symbol -> blocked BY THE HOOK"
setup "conflicted-deleted-symbol"
# The case that proves .husky/pre-commit actually calls the gates. Case 1 cannot:
# an unparseable file dies in the rustfmt block first, so removing the gates call
# from the hook leaves case 1 passing. This resolution is rustfmt-canonical and
# parses, so rustfmt exits 0 and only the gates can block it -- reached through
# `git commit`, not by invoking the script directly.
conflicted_merge 'pub fn shared() -> i32 {
    helper()
}
'
BEFORE=$(git rev-parse HEAD)
OUT=$(git commit -m "Resolve merge conflicts with main" 2>&1); RC=$?
if [ "$RC" -eq 0 ]; then
  echo "  FAIL [$CASE] .husky/pre-commit does not run the gates (merge committed, exit 0)"
  FAILURES=$((FAILURES + 1))
fi
contains "the hook ran the gates" "running cargo check --workspace"
contains "E0425" "cannot find function \`helper\`"
contains "names the failing gate" "cargo check --workspace' failed"
check "HEAD unchanged" "$BEFORE" "$(git rev-parse HEAD)"
teardown

echo "3. real main 7746d0f tree (the historical 46-minute breakage) via --merge -> exit 1"
setup "historical-7746d0f"
if git -C "$REPO_ROOT" cat-file -e 7746d0f^{commit} 2>/dev/null; then
  realtree 7746d0f
  run_gates --merge
  check "exit" 1 "$RC"
  contains "the parse error" "expected \`;\`, found keyword \`let\`"
  contains "E0425 event_rx" "cannot find value \`event_rx\`"
  contains "E0425 event_tx" "cannot find value \`event_tx\`"
  contains "E0599 with_services" "no method named \`with_services\` found"
  contains "names the failing gate" "cargo check --workspace' failed"
  contains "offers the bypass" "git commit --no-verify"
else
  # Legitimate in a shallow clone, but counted: a skip that only prints is how a
  # suite reports green while proving nothing.
  echo "  SKIP [$CASE] commit 7746d0f is not reachable from this clone"
  SKIPS=$((SKIPS + 1))
fi
teardown

echo "4. merge resolution calling a symbol the merge deleted -> rustfmt 0, gates 1"
setup "deleted-symbol"
mkcrate
# Parses and is rustfmt-canonical; only name resolution can see the problem.
printf 'pub fn shared() -> i32 {\n    helper()\n}\n' > src/lib.rs
git add Cargo.toml src/lib.rs
FMT=$(rustfmt --edition 2021 --config skip_children=true --check src/lib.rs 2>&1); FMT_RC=$?
check "rustfmt exit" 0 "$FMT_RC"
check "rustfmt silent" "" "$FMT"
run_gates --merge
check "gates exit" 1 "$RC"
contains "E0425" "cannot find function \`helper\`"
teardown

echo "5. merge resolution with needless_range_loop -> rustfmt 0, check 0, gates 1"
setup "clippy-regression"
mkcrate
printf 'pub fn shared(v: &[i32]) -> i32 {\n    let mut t = 0;\n    for i in 0..v.len() {\n        t += v[i];\n    }\n    t\n}\n' > src/lib.rs
git add Cargo.toml src/lib.rs
FMT=$(rustfmt --edition 2021 --config skip_children=true --check src/lib.rs 2>&1); FMT_RC=$?
check "rustfmt exit" 0 "$FMT_RC"
check "rustfmt silent" "" "$FMT"
CHECK_OUT=$(cargo check --workspace --quiet 2>&1); CHECK_RC=$?
check "cargo check exit" 0 "$CHECK_RC"
run_gates --merge
if command -v cargo-clippy >/dev/null 2>&1; then
  check "gates exit" 1 "$RC"
  contains "the lint" "needless_range_loop"
  contains "names the failing gate" "clippy --workspace --all-targets' failed"
else
  echo "  SKIP [$CASE] cargo-clippy absent; asserting the skip path instead"
  SKIPS=$((SKIPS + 1))
  check "gates exit" 0 "$RC"
  contains "skip message" "cargo-clippy not found"
fi
teardown

echo "6. healthy tree (current HEAD) via --merge -> exit 0"
setup "healthy-head"
realtree HEAD
run_gates --merge
check "exit" 0 "$RC"
contains "ran check" "running cargo check --workspace"
missing "no error" "ERROR:"
teardown

echo "7. ordinary commit on a broken tree, no MERGE_HEAD, no flag -> exit 0, no cargo"
setup "ordinary-commit"
mkcrate
printf 'pub fn shared() -> i32 {\n    let x = 1\n}\n' > src/lib.rs
git add Cargo.toml src/lib.rs
START=$(date +%s)
run_gates
ELAPSED=$(( $(date +%s) - START ))
check "exit" 0 "$RC"
check "silent" "" "$OUT"
if [ "$ELAPSED" -gt 5 ]; then
  echo "  FAIL [$CASE] took ${ELAPSED}s; cargo was probably invoked"
  FAILURES=$((FAILURES + 1))
fi
teardown

echo "8. merge staging only README.md -> exit 0, no cargo"
setup "no-rust-staged"
mkcrate
printf 'pub fn shared() -> i32 {\n    0\n}\n' > src/lib.rs
git add Cargo.toml src/lib.rs
git commit -qm base --no-verify
printf 'docs\n' > README.md
git add README.md
run_gates --merge
check "exit" 0 "$RC"
contains "skip message" "Merge touches no Rust files"
missing "did not run cargo" "running cargo check"
teardown

echo "9. clean auto-merge -> pre-merge-commit fires and blocks (MERGE_HEAD absent there)"
setup "clean-auto-merge"
# No reachability guard here: this case builds its own fixture and never touches
# the real repo's history, so a guard could only ever skip it silently.
mkcrate
# 60 lines apart, so git merges both edits without a conflict. The union does
# not compile: one side removed helper(), the other side added a call to it.
{
  printf 'pub fn helper() -> i32 {\n    7\n}\n\n'
  i=0
  while [ "$i" -lt 20 ]; do printf 'pub fn pad%d() {}\n' "$i"; i=$((i + 1)); done
  printf '\npub fn tail() -> i32 {\n    0\n}\n'
} > src/lib.rs
git add Cargo.toml src/lib.rs
git commit -qm base --no-verify
git checkout -q -b side
# side: call helper() from tail()
sed 's/^    0$/    helper()/' src/lib.rs > t && mv t src/lib.rs
git commit -qam "side calls helper" --no-verify
git checkout -q -
# mainline: delete helper() entirely
sed '1,4d' src/lib.rs > t && mv t src/lib.rs
git commit -qam "mainline drops helper" --no-verify
# Record what the hook sees at the moment it runs. This is the trap the
# --merge argument exists for: a MERGE_HEAD-only trigger looks correct and
# never fires here. Asserted from inside the hook, because git writes
# MERGE_HEAD *after* the hook refuses (so the merge can be concluded by hand)
# and checking afterwards reports PRESENT for the wrong reason.
PROBE="$SCRATCH/probe.txt"
cat > src/frontend/.husky/pre-merge-commit <<PROBEHOOK
#!/bin/sh
[ -f "\$(git rev-parse --git-dir)/MERGE_HEAD" ] && echo "MERGE_HEAD=PRESENT" > "$PROBE" || echo "MERGE_HEAD=ABSENT" > "$PROBE"
echo "ARGS=[\$*]" >> "$PROBE"
echo "STAGED_RS=\$(git diff --cached --name-only -z --diff-filter=ACMR | tr '\\0' '\\n' | grep -c '\\.rs\$')" >> "$PROBE"
exec sh -e "\$(git rev-parse --show-toplevel)/scripts/precommit-rust-gates.sh" --merge
PROBEHOOK
chmod 755 src/frontend/.husky/pre-merge-commit
OUT=$(git merge side -m "Merge side" 2>&1); RC=$?
if [ "$RC" -eq 0 ]; then
  echo "  FAIL [$CASE] clean auto-merge committed despite not compiling (exit 0)"
  FAILURES=$((FAILURES + 1))
fi
contains "git reports the hook refused" "Not committing merge"
contains "the compile error" "cannot find function \`helper\`"
check "hook fired at all" "yes" "$([ -f "$PROBE" ] && echo yes || echo no)"
check "MERGE_HEAD absent when the hook runs" "MERGE_HEAD=ABSENT" "$(sed -n 1p "$PROBE" 2>/dev/null)"
# git passes no arguments to pre-merge-commit, which is why the hook has to
# supply --merge itself rather than inferring the merge from its argv.
check "git passes no arguments" "ARGS=[]" "$(sed -n 2p "$PROBE" 2>/dev/null)"
check "a .rs file was staged" "STAGED_RS=1" "$(sed -n 3p "$PROBE" 2>/dev/null)"
check "merge not committed" "1" "$(git rev-list --parents -n 1 HEAD | wc -w | tr -d ' ' | awk '{print $1-1}')"
teardown

echo ""
if [ "$FAILURES" -eq 0 ]; then
  if [ "$SKIPS" -eq 0 ]; then
    echo "ALL 10 CASES PASS"
  else
    echo "ALL 10 CASES PASS ($SKIPS skipped - see SKIP lines above)"
  fi
  exit 0
fi
echo "FAILURES: $FAILURES  SKIPS: $SKIPS"
exit 1
